language: scala
scala:
  - 2.10.3
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
env:
  global:
    - secure: "l+u3rdwefma/qVV3o2bP/MEklVp1hiDfTZoZirR8nWfMghnh2bUBejesM3+eryKAzMSRMS+obKczNs4RCoAHaKaTF9KiD+FNYN93p3yL51FwA2SB0Y6aIv86KCrhLY/LHE/jkqB5Anr+rGMt4V5ChkJciN3yT+nPUYBo26rk7es="
    - secure: "Vr72Us0cRjezx44naDLtXWXnaGOi29rUTnSOUEY0eCU8nt8uGRS8bK1rK4ppxMVjSBqcatHTXtwXPvVEYIfnUs/KcsVoQeqLLrGFM8nETp16GtdjXCzJEqEKOIoJhoHDWQGawBQeOeXaqBSy3yqYpiBEWd+ujA0zjpTZakPGE3k="
after_success:
  - sbt publish
notifications:
  email:
     - corey.jon.oliver@gmail.com